trigger:
- main  # Or your main branch

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '94f5cfc1-06a4-4858-93fa-54b1083eab1c'
  # Agent VM image name
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  displayName: 'Build and Unit Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDK version'
    jdkVersionOption: '1.8' # Adjust as needed
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'

- task: SonarQubePrepare@5
  displayName: 'Prepare SonarQube Analysis'
  inputs:
    SonarQube: 'YourSonarQubeConnection' # Replace with your SonarQube service connection name
    scannerMode: 'MSBuild' # Or 'Standalone' if not using MSBuild
    projectKey: 'your-project-key' # Define a unique key for your project in SonarQube
    projectName: 'Your Project Name'

- task: Maven@3
  displayName: 'Run SonarQube Analysis'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDK version'
    jdkVersionOption: '1.8' # Adjust as needed
    jdkArchitectureOption: 'x64'
    goals: 'org.sonarsource.scanner.maven:sonar-maven-plugin:sonar'

- task: SonarQubePublish@5
  displayName: 'Publish SonarQube Quality Gate Result'
  inputs:
    pollingTimeoutSec: '300'

- task: PublishCodeCoverageResults@2
  displayName: 'Publish Code Coverage'
  inputs:
    codeCoverageTool: 'JaCoCo' # Or 'Cobertura' if you use that
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml' # Adjust path if needed
    reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'

- task: CopyFiles@2
  displayName: 'Copy Artifacts'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/target/*.?(war|jar)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
